SELECT CUSTOMERS.NAME AS 'Nome do Cliente',
       CARS.NAME AS 'Carro',
       EMPLOYEES.NAME AS 'Funcionário' FROM LOCATIONS
INNER JOIN CUSTOMERS ON (CUSTOMERS.ID = LOCATIONS.CUSTOMER_ID)
INNER JOIN EMPLOYEES ON (EMPLOYEES.ID = LOCATIONS.EMPLOYEE_ID)
INNER JOIN CARS ON (CARS.ID = LOCATIONS.CAR_ID)